version: '3.8'

services:
  nestjs-app:
    build: .
    container_name: nestjs-app
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: oncology
      DB_PASS: oncology
      DB_NAME: oncology

  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oncology
      POSTGRES_PASSWORD: oncology
      POSTGRES_DB: oncology
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
